export const SECTION_SUB_TEXT = 'What I have done so far'
export const SECTION_HEAD_TEXT = 'Work Experience.'

export const EXPERIENCE_ICON_CLASSES = 'w-[60%] h-[60%] object-contain'
export const EXPERIENCE_ICON_WRAPPER_CLASSES = 'flex justify-center items-center w-full h-full'
export const EXPERIENCE_CARD_TITLE_CLASSES = 'text-white text-[24px] font-bold'
export const EXPERIENCE_CARD_2TITLE_CLASSES = 'text-white text-[18px] font-bold'
export const EXPERIENCE_CARD_SUB_TITLE_CLASSES = 'text-secondary text-[16px] font-semibold'
export const EXPERIENCE_CARD_POINTS_CLASSES = 'mt-5 list-disc ml-5 space-y-2'
export const EXPERIENCE_CARD_POINT_CLASSES = 'text-white-100 text-[14px] pl-1 tracking-wider'
